# ANN

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

import keras
from keras.models import Sequential 
from keras.layers import Dense

C:\Users\admin\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


** Read Data **

In [2]:
data = pd.read_csv('2_Churn_Modelling.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


** Predict if the user will buy SUV based on Age and EstimatedSalary **

In [3]:
x = data.iloc[:,3:13].values
y = data.iloc[:,13].values

** One Hot Encoding ** 

In [4]:
le1 = LabelEncoder()
x[:,1] = le1.fit_transform(x[:,1])
le2 = LabelEncoder()
x[:,2] = le2.fit_transform(x[:,2])

In [5]:
ohe = OneHotEncoder(categorical_features=[1])
x = ohe.fit_transform(x).toarray()
x = x[:,1:]

** Split the data **

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state = 0)

** Feature Scaling **

In [7]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

** ANN **

In [8]:
classifier = Sequential()
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\admin\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=6, input_dim=11)`
  
C:\Users\admin\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=6, activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\admin\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=1, activation="sigmoid")`
  after removing the cwd from sys.path.


In [9]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

** Fitting the model **

In [10]:
classifier.fit(x_train, y_train, batch_size=10, nb_epoch= 100)

C:\Users\admin\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py:981: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
7500/7500 [==============================] - 3s 374us/step - loss: 0.4956 - acc: 0.7971
Epoch 2/100
7500/7500 [==============================] - 3s 383us/step - loss: 0.4103 - acc: 0.8253
Epoch 3/100
7500/7500 [==============================] - 2s 258us/step - loss: 0.3969 - acc: 0.8304
Epoch 4/100
7500/7500 [==============================] - 2s 271us/step - loss: 0.3889 - acc: 0.8299
Epoch 5/100
7500/7500 [==============================] - 2s 285us/step - loss: 0.3829 - acc: 0.8321
Epoch 6/100
7500/7500 [==============================] - 2s 253us/step - loss: 0.3770 - acc: 0.8315
Epoch 7/100
7500/7500 [==============================] - 2s 291us/step - loss: 0.3725 - acc: 0.8437
Epoch 8/100
7500/7500 [==============================] - 2s 246us/step - loss: 0.3692 - acc: 0.8475
Epoch 9/100
7500/7500 [==============================] - 2s 287us/step - loss: 0.3664 - acc: 0.8499
Epoch 10/100
7500/7500 [==============================] - 2s 254us/step - loss: 0.3642 - acc: 0.8521

7500/7500 [==============================] - 2s 316us/step - loss: 0.3353 - acc: 0.8621
Epoch 81/100
7500/7500 [==============================] - 2s 304us/step - loss: 0.3348 - acc: 0.8643
Epoch 82/100
7500/7500 [==============================] - 2s 323us/step - loss: 0.3354 - acc: 0.8636
Epoch 83/100
7500/7500 [==============================] - 2s 317us/step - loss: 0.3346 - acc: 0.8637
Epoch 84/100
7500/7500 [==============================] - 2s 309us/step - loss: 0.3345 - acc: 0.8592
Epoch 85/100
7500/7500 [==============================] - 2s 300us/step - loss: 0.3350 - acc: 0.8640
Epoch 86/100
7500/7500 [==============================] - 2s 295us/step - loss: 0.3346 - acc: 0.8636
Epoch 87/100
7500/7500 [==============================] - 2s 315us/step - loss: 0.3351 - acc: 0.8613
Epoch 88/100
7500/7500 [==============================] - 2s 302us/step - loss: 0.3355 - acc: 0.8615
Epoch 89/100
7500/7500 [==============================] - 2s 314us/step - loss: 0.3348 - acc: 0.8628
Epo

** Predict Test **

In [11]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

** Evaluate the preformance **

In [12]:
cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
cm

array([[1891,  100],
       [ 252,  257]], dtype=int64)

** New prediction ** 

In [13]:
new_prediction = classifier.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))
new_prediction = (new_prediction > 0.5)
new_prediction

C:\Users\admin\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[False]])